name: id_checker
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

dependencies:
  args: ^2.5.0
  dartz: ^0.10.1
  http: ^1.2.1
  json_annotation: ^4.9.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.7
